-- AlterTable (Hotel)
ALTER TABLE "Hotel" ADD COLUMN "contactEmail" TEXT;
ALTER TABLE "Hotel" ADD COLUMN "contactPhone" TEXT;
ALTER TABLE "Hotel" ADD COLUMN "heroTitle" TEXT;
ALTER TABLE "Hotel" ADD COLUMN "heroDescription" TEXT;

-- AlterTable (RoomType)
ALTER TABLE "RoomType" ADD COLUMN "images" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "RoomType" ADD COLUMN "description" TEXT;
ALTER TABLE "RoomType" ADD COLUMN "basePrice" INTEGER;
ALTER TABLE "RoomType" ADD COLUMN "maxAdults" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "RoomType" ADD COLUMN "maxChildren" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RoomType" ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "RoomType" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "RoomType" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "RoomType" ADD COLUMN "deletedAt" TIMESTAMP(3);

-- AlterTable (Room)
ALTER TABLE "Room" ADD COLUMN "roomNumber" TEXT;
ALTER TABLE "Room" ADD COLUMN "deletedAt" TIMESTAMP(3);
